name: Build with vcpkg

permissions:
  contents: read

on:
  push:
    branches:
      - dev
      - v*

    paths:
      - .github/workflows/build-vcpkg.yml
      - cmake/**
      - src/**
      - CMakeLists.txt
      - CMakePresets.json
      - vcpkg.json

  pull_request:
    paths:
      - .github/workflows/build-vcpkg.yml
      - cmake/**
      - src/**
      - CMakeLists.txt
      - CMakePresets.json
      - vcpkg.json

jobs:
  build-vcpkg:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu, windows]

    env:
      VCPKG_BUILD_TYPE: release
      VCPKG_INSTALLED_DIR: ${{ github.workspace }}/vcpkg_installed
      VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg_cache
      VCPKG_BINARY_SOURCES: clear;files,${{ github.workspace }}/vcpkg_cache,readwrite

    steps:
      - uses: actions/checkout@v6

      - name: Create vcpkg binary cache directory
        run: mkdir -p "${{ github.workspace }}/vcpkg_cache"
        shell: bash

      - run: echo CXX=g++-14 >> $GITHUB_ENV
        if: ${{ matrix.os == 'ubuntu' }}

      - name: Get latest CMake
        uses: lukka/get-cmake@latest

      - name: Cache vcpkg binary packages
        uses: actions/cache@v5
        with:
          path: ${{ github.workspace }}/vcpkg_cache
          key: vcpkg-binary-${{ matrix.os }}-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            vcpkg-binary-${{ matrix.os }}-

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          doNotCache: false

      - name: Build with CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: vcpkg
          buildPreset: vcpkg
          buildPresetAdditionalArgs: "['--config', 'Debug']"

      - name: Upload build logs
        uses: actions/upload-artifact@v7
        with:
          name: logs-${{ matrix.os }}-${{ github.sha }}
          path: ${{ github.workspace }}/vcpkg/buildtrees/**/*.log
        if: ${{ failure() }}

      - name: Upload artifact binary
        uses: actions/upload-artifact@v7
        if: ${{ !startsWith(matrix.os, 'windows') }}
        with:
          name: tfs-${{ matrix.os }}-${{ github.sha }}
          path: ${{ github.workspace }}/build/Debug/tfs

      - name: Upload artifact binary (exe)
        uses: actions/upload-artifact@v7
        if: ${{ startsWith(matrix.os, 'windows') }}
        with:
          name: tfs-${{ matrix.os }}-${{ github.sha }}
          path: |
            ${{ github.workspace }}/build/Debug/tfs.exe
            ${{ github.workspace }}/build/Debug/*.dll
