name: Unit tests

permissions:
  contents: read

on:
  push:
    branches:
      - dev

  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mariadb

        env:
          MARIADB_USER: atlas
          MARIADB_PASSWORD: atlas
          MARIADB_DATABASE: atlas
          MARIADB_INITDB_SKIP_TZINFO: "yes"
          MARIADB_RANDOM_ROOT_PASSWORD: "yes"

        options: --health-cmd="healthcheck.sh --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=3

        ports:
          - 3306:3306

    env:
      CXX: g++-14
      VCPKG_BUILD_TYPE: release
      VCPKG_INSTALLED_DIR: ${{ github.workspace }}/vcpkg_installed
      VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg_cache
      VCPKG_BINARY_SOURCES: clear;files,${{ github.workspace }}/vcpkg_cache,readwrite

    steps:
      - uses: actions/checkout@v6

      - name: Create vcpkg binary cache directory
        run: mkdir -p "${{ github.workspace }}/vcpkg_cache"

      - name: Get latest CMake
        uses: lukka/get-cmake@latest

      - name: Cache vcpkg binary packages
        uses: actions/cache@v5
        with:
          path: ${{ github.workspace }}/vcpkg_cache
          key: vcpkg-binary-ubuntu-test-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            vcpkg-binary-ubuntu-test-

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          doNotCache: false

      - name: Setup database
        run: |
          sudo apt update -qq
          sudo apt install -yqq mariadb-client
          mysql -h 0.0.0.0 -u atlas -patlas atlas < schema.sql

      - name: Build with CMake
        uses: lukka/run-cmake@v10
        env:
          ASAN_OPTIONS: exitcode=0
          LSAN_OPTIONS: exitcode=0
        with:
          configurePreset: vcpkg
          configurePresetAdditionalArgs: "['-DBUILD_TESTING=ON', '-DENABLE_ASAN=ON']"
          buildPreset: vcpkg
          buildPresetAdditionalArgs: "['--config', 'Debug']"
          testPreset: vcpkg
          testPresetAdditionalArgs: "['--build-config', 'Debug']"
